# Generated by Django 3.1.5 on 2021-02-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='short_name',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
